# Generated by Django 4.2.30 on 2026-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='CUSTOMER', max_length=10),
        ),
    ]
